added renderer.js, ipc, and react
sdsanders/kill-the-mouse pull request #12
Opened 2018-06-15 06:59 UTC by justinschuldt

@sdsanders added two things:

- ipc for sending messages between the main and render processes.
- react, ReactDOM to render it without building. Had to set the `<script>`'s type to `text/bable` in order to use JSX in `renderer.js`. Brought bable in with a script tag, idk how else to make bable available there. There is an npm package for `bable-standalone`, couldn't get it to work though.

There is a high score list in the client, ipc messages are just added to an array in the component's state. This works but I think this kind of state is better suited for `main.js`. That way we could send out notifications when you broke your previous high score, etc.

fixes:
https://github.com/sdsanders/kill-the-mouse/issues/2, https://github.com/sdsanders/kill-the-mouse/issues/4, https://github.com/sdsanders/kill-the-mouse/issues/5, https://github.com/sdsanders/kill-the-mouse/issues/9

2018-06-19 23:26 UTC, sdsanders requested changes

2018-07-16 14:16 UTC, justinschuldt commented
@sdsanders yooo

2018-07-23 01:02 UTC, sdsanders approved these changes

2018-07-23 01:03 UTC, sdsanders commented
Looks good, thanks man!

2018-07-23 01:04 UTC, merged